version: "3.7"
services:
  db:
    image: postgres:12
    container_name: CitrusTrack-DB
    environment:
      POSTGRES_USER: mac
      POSTGRES_PASSWORD: mac1996
      POSTGRES_DB: CitrusTrack
    ports:
      - "5438:5432"
    volumes:
      - ./db:/var/lib/postgresql/data